// SPDX-License-Identifier: GPL-2.0-or-later
// Station-log test: ADIF parse/write round-trip, LogDb insert + duplicate-
// skipping import, LogbookIndex's merged worked-before view and the
// country/band/mode needed-status dimensions, and the bearing math the
// LOG window's SP/LP rotor buttons use. No hardware, no network.
#include <QCoreApplication>
#include <QBuffer>
#include <QTemporaryDir>
#include <QTimeZone>
#include <cmath>
#include <cstdio>

#include <QFile>

#include "log/Adif.h"
#include "log/LogDb.h"
#include "util/Bearing.h"
#include "util/CtyLookup.h"
#include "util/LogbookIndex.h"

using namespace ttc;

static int fails = 0;
#define CHECK(cond, what)                                                  \
    do {                                                                   \
        if (cond) {                                                        \
            std::printf("ok    %s\n", what);                               \
        } else {                                                           \
            std::printf("FAIL  %s\n", what);                               \
            ++fails;                                                       \
        }                                                                  \
    } while (0)

static void testAdif() {
    const QByteArray adi =
        "Generated by something\n"
        "<ADIF_VER:5>3.1.4 <EOH>\n"
        "<CALL:5>V26OC <QSO_DATE:8>20260901 <TIME_ON:4>1916 "
        "<BAND:3>12M <FREQ:9>24.915200 <MODE:2>CW <RST_SENT:3>599 "
        "<RST_RCVD:3>599 <LOTW_QSL_RCVD:1>Y <EOR>\n"
        "<CALL:6>SA6LKX <QSO_DATE:8>20260901 <TIME_ON:6>102200 "
        "<FREQ:9>14.035000 <MODE:2>CW <SIG:4>POTA <SIG_INFO:7>SE-2129 "
        "<EOR>\n";
    const auto recs = Adif::parseBytes(adi);
    CHECK(recs.size() == 2, "adif: two records parsed");
    CHECK(recs[0].value("CALL") == "V26OC", "adif: call field");
    CHECK(recs[0].value("BAND") == "12M", "adif: band field");

    Qso q = LogDb::fromAdif(recs[0]);
    CHECK(q.call == "V26OC" && q.band == "12M" && q.mode == "CW",
          "fromAdif: identity fields");
    CHECK(q.freqHz == 24915200, "fromAdif: frequency in Hz");
    CHECK(q.lotwRcvd == "Y", "fromAdif: LoTW confirmation");
    CHECK(q.tsUtc.toString("yyyyMMdd HHmm") == "20260901 1916",
          "fromAdif: timestamp");

    Qso p = LogDb::fromAdif(recs[1]);
    CHECK(p.band == "20M", "fromAdif: band derived from frequency");
    CHECK(p.pota == "SE-2129", "fromAdif: POTA via SIG/SIG_INFO");

    // Round trip: Qso -> record -> text -> record -> Qso.
    const QString txt = Adif::writeRecord(LogDb::toAdif(q));
    const auto back = Adif::parseBytes(txt.toUtf8());
    CHECK(back.size() == 1, "adif: round-trip parses");
    const Qso q2 = LogDb::fromAdif(back[0]);
    CHECK(q2.call == q.call && q2.band == q.band && q2.mode == q.mode
              && q2.freqHz == q.freqHz && q2.lotwRcvd == "Y"
              && q2.tsUtc == q.tsUtc,
          "adif: round-trip is lossless");
}

static void testLogDb(const QString& dir) {
    LogDb db;
    CHECK(db.open(dir + "/log.sqlite"), "logdb: opens");

    Qso q;
    q.call = "k8qbs";                       // stored uppercased
    q.tsUtc = QDateTime::fromString("2026-08-31 22:45:00",
                                    "yyyy-MM-dd HH:mm:ss");
    q.tsUtc.setTimeZone(QTimeZone::utc());
    q.freqHz = 7036000;
    q.band = "40M";
    q.mode = "CW";
    q.rstS = "599";
    q.rstR = "599";
    q.country = "United States";
    CHECK(db.addQso(q) > 0, "logdb: insert");
    CHECK(db.count() == 1, "logdb: count");
    CHECK(db.prevQsos("K8QBS").size() == 1, "logdb: prevQsos finds it");

    // Import: one new, one duplicate of the row above (2 min off), one new.
    const QByteArray adi =
        "<EOH>\n"
        "<CALL:5>K8QBS <QSO_DATE:8>20260831 <TIME_ON:6>224700 "
        "<BAND:3>40M <MODE:2>CW <EOR>\n"
        "<CALL:6>LA1MFA <QSO_DATE:8>20260829 <TIME_ON:4>1905 "
        "<FREQ:9>21.014000 <MODE:2>CW <COUNTRY:6>Norway <EOR>\n"
        "<CALL:5>4L5O <QSO_DATE:8>20260901 <TIME_ON:4>1900 "
        "<BAND:3>20M <MODE:3>SSB <COUNTRY:7>Georgia <QSL_RCVD:1>Y <EOR>\n";
    QBuffer buf;
    buf.setData(adi);
    buf.open(QIODevice::ReadOnly);
    const int n = db.importAdif(buf, nullptr);
    CHECK(n == 2, "logdb: import adds 2, skips the near-duplicate");
    CHECK(db.count() == 3, "logdb: count after import");

    // Export -> parse -> same number of records.
    QBuffer out;
    out.open(QIODevice::WriteOnly);
    CHECK(db.exportAdif(out), "logdb: export runs");
    const auto recs = Adif::parseBytes(out.data());
    CHECK(recs.size() == 3, "logdb: export carries every QSO");

    // Upload bookkeeping: live QSOs queue; imported HISTORY never does
    // (imports are stamped sent, so a 13k archive can't trigger a storm).
    auto pend = db.pendingUploads("eqsl");
    CHECK(pend.size() == 1 && pend[0].call == "K8QBS",
          "uploads: only the live QSO is pending");
    CHECK(db.setUploadState(pend[0].id, "eqsl", 'Y'),
          "uploads: state update");
    CHECK(db.pendingUploads("eqsl").isEmpty(),
          "uploads: sent leaves the queue");
}

static void testIndex(const QString& dir) {
    LogDb db;
    db.open(dir + "/idx.sqlite");
    const auto add = [&db](const char* call, const char* band,
                           const char* mode, const char* country,
                           const char* lotw) {
        Qso q;
        q.call = call;
        q.band = band;
        q.mode = mode;
        q.country = country;
        q.lotwRcvd = lotw;
        q.freqHz = 14000000;
        q.tsUtc = QDateTime::currentDateTimeUtc();
        db.addQso(q);
    };
    add("LA1MFA", "15M", "CW", "Norway", "Y");
    add("SA6LKX", "20M", "CW", "Sweden", "");

    LogbookIndex idx;
    idx.attachDb(&db);

    CHECK(idx.ready(), "index: db source makes it ready");
    CHECK(idx.status("LA1MFA", "15M") == 'C', "index: confirmed this band");
    CHECK(idx.status("LA1MFA", "20M") == 'B', "index: worked, other band");
    CHECK(idx.status("SA6LKX", "20M") == 'W', "index: worked this band");
    CHECK(idx.status("ZL1XYZ", "20M") == 'N', "index: never worked");

    // Country-centric needed-status (no cty attached: country from rows).
    auto nd = idx.need("LA1MFA", "15M", "CW");
    CHECK(nd.country == 'C' && nd.band == 'C' && nd.mode == 'C',
          "need: confirmed country/band/mode");
    nd = idx.need("LA1MFA", "20M", "SSB");
    CHECK(nd.country == 'C' && nd.band == 'N' && nd.mode == 'N',
          "need: new band and mode for a confirmed country");
    nd = idx.need("SA6LKX", "20M", "CW");
    CHECK(nd.country == 'W' && nd.band == 'W' && nd.mode == 'W',
          "need: worked, unconfirmed");

    // A new QSO flips the sets live (LogDb::changed -> refreshDb).
    add("ZL1XYZ", "20M", "CW", "New Zealand", "");
    CHECK(idx.status("ZL1XYZ", "20M") == 'W', "index: follows live inserts");

    // The LoTW QSL download marks matching QSOs confirmed — call, band,
    // mode and the QSO date (with the ±1 day UTC tolerance).
    AdifRecord qsl;
    qsl.insert("CALL", "SA6LKX");
    qsl.insert("BAND", "20M");
    qsl.insert("MODE", "CW");
    qsl.insert("QSO_DATE", QDateTime::currentDateTimeUtc()
                               .addDays(1).toString("yyyyMMdd"));
    qsl.insert("QSL_RCVD", "Y");
    CHECK(db.applyLotwConfirmations({qsl}) == 1,
          "lotw sync: report record marks the QSO");
    CHECK(idx.status("SA6LKX", "20M") == 'C',
          "lotw sync: confirmation reaches the worked-before view");
    CHECK(db.applyLotwConfirmations({qsl}) == 0,
          "lotw sync: already-confirmed QSOs don't count again");
}

static void testCountryVocabulary(const QString& dir) {
    // The live bug: cty.dat says "Fed. Rep. of Germany", the imported log
    // said "Fed. Republic of Germany", and every German spot showed as
    // needed. Both sides must canonicalize through cty.dat by callsign.
    const QString ctyPath = dir + "/mini-cty.dat";
    {
        QFile f(ctyPath);
        f.open(QIODevice::WriteOnly | QIODevice::Text);
        f.write("Fed. Rep. of Germany:     14:  28:  EU:   51.00:"
                "   -10.00:    -1.0:  DL:\n"
                "    DA,DB,DC,DD,DE,DF,DG,DH,DJ,DK,DL,DM;\n");
    }
    CtyLookup cty;
    CHECK(cty.load(ctyPath), "cty: mini file loads");

    LogDb db;
    db.open(dir + "/vocab.sqlite");
    Qso q;
    q.call = "DL1ABC";
    q.band = "20M";
    q.mode = "CW";
    q.country = "Fed. Republic of Germany";     // the ADIF spelling
    q.lotwRcvd = "Y";
    q.freqHz = 14020000;
    q.tsUtc = QDateTime::currentDateTimeUtc();
    db.addQso(q);

    LogbookIndex idx;
    idx.attachCty(&cty);
    idx.attachDb(&db);
    // A DIFFERENT German call, never worked: the country dim must still
    // say confirmed — same entity, whatever the log's export called it.
    const auto nd = idx.need("DK5XYZ", "20M", "CW");
    CHECK(nd.country == 'C',
          "vocabulary: spelling mismatch can't hide a confirmed country");
    CHECK(nd.band == 'C' && nd.mode == 'C',
          "vocabulary: band and mode dims ride the same canonical name");
}

static void testBearing() {
    // Toledo (EN83) to Antigua (FK97): south-east, ~3300 km.
    const double az = bearing::initialDeg(41.6, -83.7, 17.1, -61.8);
    const double km = bearing::distanceKm(41.6, -83.7, 17.1, -61.8);
    CHECK(std::abs(az - 136.0) < 4.0, "bearing: Toledo->Antigua heading");
    CHECK(std::abs(km - 3400.0) < 200.0, "bearing: Toledo->Antigua distance");
    CHECK(std::abs(bearing::initialDeg(0, 0, 0, 90) - 90.0) < 0.01,
          "bearing: due east along the equator");
}

int main(int argc, char** argv) {
    QCoreApplication app(argc, argv);
    QTemporaryDir tmp;
    if (!tmp.isValid()) {
        std::printf("FAIL  no temp dir\n");
        return 1;
    }
    testAdif();
    testLogDb(tmp.path());
    testIndex(tmp.path());
    testCountryVocabulary(tmp.path());
    testBearing();
    std::printf(fails ? "LOGTEST: FAIL (%d)\n" : "LOGTEST: PASS\n", fails);
    return fails ? 1 : 0;
}
